# Discord #

# Discord bot token
DISCORD_TOKEN: ""
# Discord bot prefix
PREFIX: ""
# Discord logs channel id
LOGS_CHANNEL: 
# Discord warn member id
WARN_MEMBERS_ID: 
  - ID1
  - ID2
  - ID3

# Luraph #

# Luraph API Key
LURAPH_API_KEY: ""